/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cognizant.scope;

public class App {

    public static void main(String[] args) {

        ConnectionPool pool = new ConnectionPool(5);
        try(Connection connection = pool.getConnection()) {
            throw new RuntimeException("Kaboom!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
